
{% extends "templates/index.phtml" %}

{% block titulo %} Departamentos {% endblock %}
{% block cuerpo %}

<script>

var departament={{departament | json_encode}};
console.log(departament);
        
</script>
<div id="panel">
    <div class="listaBotones" style="float: left;">
        <ul>
            <li id="botonDepto1"><span>Cremeria y Salchichoneria</span></li>
            <li id="botonDepto2"><span>Frutas y verduras</span></li>
            <li id="botonDepto3"><span>Panaderia</span></li>
            <li id="botonDepto4"><span>Farmacia</span></li>
            <li id="botonDepto5"><span>Abarrotes</span></li>
            <li id="botonDepto6"><span>Baños</span></li>
            <li id="botonDepto7"><span>Cajas</span></li>
        </ul>
    </div>
    <div id="mapaDiv">
        <img src="img/planoTienda.png"  style="border:1px solid black;"/>
        <a href="departamentos/productos?departament_id=10"><div class="deptos" id="depto1">
           <span style="height:50px;width: 150px">Deportes
               <br>Presione para ver lista</span>
            </div></a>
        <a href="departamentos/productos?departament_id=7"><div class="deptos" id="depto2">
           <span style="height:50px;width: 150px">Ferreteria
               <br>Presione para ver lista</span>
            </div></a>
        <a href="departamentos/productos?departament_id=2"><div class="deptos" id="depto3">
           <span style="height:50px;width: 150px">Frutas y Verduras
               <br>Presione para ver lista</span>
            </div></a>
        <a href="departamentos/productos?departament_id=11"><div class="deptos" id="depto4">
           <span style="height:50px;width: 150px">Jugueteria
               <br>Presione para ver lista</span>
            </div></a>
        <a href="departamentos/productos?departament_id=9"><div class="deptos" id="depto5">
           <span style="height:50px;width: 150px">Papeleria
               <br>Presione para ver lista</span>
            </div></a>
        <a href="departamentos/productos?departament_id=8"><div class="deptos" id="depto6">
           <span style="height:50px;width: 150px">Vestimenta
               <br>Presione para ver lista</span>
            </div></a>
        <a href="departamentos/productos?departament_id=1"><div class="deptos" id="depto7">
           <span style="height:50px;width: 150px">Cremeria y Salchichoneria
               <br>Presione para ver lista</span>
            </div></a>
       <a href="departamentos/productos?departament_id=3"><div class="deptos" id="depto8">
           <span style="height:30px;">Panaderia
               <br>Presione para ver lista</span>
            </div></a>
       <div class="deptos" id="depto9">
           <span style="height:15px;width: 150px">Cajas
            </div>
       <a href="departamentos/productos?departament_id=12"><div class="deptos" id="depto10">
           <span style="height:30px;width: 200px">Entretenimiento
               <br>Presione para ver lista</span>
            </div></a>
       <a href="departamentos/productos?departament_id=4"><div class="deptos" id="depto11">
           <span style="height:30px;width: 200px">Farmacia
               <br>Presione para ver lista</span>
            </div></a>
       <a href="departamentos/productos?departament_id=6"><div class="deptos" id="depto12">
           <span style="height:35px;width: 200px">Electronica
               <br>Presione para ver lista</span>
            </div></a><a href="departamentos/productos?departament_id=6"><div class="deptos" id="depto13">
           <span style="height:35px;width: 200px">Electronica
               <br>Presione para ver lista</span>
            </div></a>
       <a href="departamentos/productos?departament_id=5"><div class="deptos" id="depto14">
           <span style="height:150px;width: 30px">A<br>b<br>a<br>r<br>r<br>o<br>t<br>e<br>s
               </span>
            </div></a>
       <div class="deptos" id="depto15">
           <span style="height:15px;width: 40px">Baños
            </div>
    </div>
    <div class="listaBotones" style="float: right;">
        <ul>
            <li id="botonDepto8"><span>Electronica</span></li>
            <li id="botonDepto9"><span>Ferreteria</span></li>
            <li id="botonDepto10"><span>Vestimenta</span></li>
            <li id="botonDepto11"><span>Papeleria</span></li>
            <li id="botonDepto12"><span>Deportes</span></li>
            <li id="botonDepto13"><span>Jugueteria</span></li>
            <li id="botonDepto14"><span>Entretenimiento</span></li>
        </ul>
    </div>
</div>
<style>
    #cuerpo{
        margin: 0px;
        position: absolute;
        top: 0px;
        height: 100%;
        width: 100%;
    }
    
    body{
        background-image: url("img/congruent_pentagon_red.png");
    }
</style>
<script>
    botonesClick();
</script>

{% endblock %}