
{% extends "templates/index.phtml" %}

{% block titulo %} Departamentos {% endblock %}
{% block cuerpo %}
<div>
    <ul>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
    </ul>
</div>
<div style="position: absolute; width: ">
    <div></div>
    <div></div>
    <div></div>
    <div></div>
    <div></div>
    <div></div>
    <div></div>
    <div></div>
    <div></div>
    <div></div>
    <div></div>
    <div></div>
    <img src="img/planoTienda.png" style="width: 100%"/>
</div>
<div>
    <ul>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
    </ul>
</div>
<style>
    body{
        background-image: url("img/congruent_pentagon_red.png");
    }
</style>


{% endblock %}