
{% extends "templates/index.phtml" %}

{% block titulo %} Departamentos {% endblock %}
{% block cuerpo %}
<div style="position: absolute; top: 0px; bottom: 0px; margin: auto;">
    <div class="listaBotones" style="float: left;">
        <ul>
            <li>Cremeria y Salchichoneria</li>
            <li>Frutas y verduras</li>
            <li>Panaderia</li>
            <li>Farmacia</li>
            <li>Cajas</li>
            <li>Baños</li>
            <li>Abarrotes</li>
        </ul>
    </div>
    <div style="display: inline-block;">
        <img src="img/planoTienda.png" style=""/>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
    </div>
    <div class="listaBotones" style="float: right;">
        <ul>
            <li>Electronica</li>
            <li>Ferreteria</li>
            <li>Ropa</li>
            <li>Papeleria</li>
            <li>Deportes</li>
            <li>Jugueteria</li>
            <li>Entretenimiento</li>
        </ul>
    </div>
</div>
<style>
    #cuerpo{
        height: 100%;
        width: 100%;
    }
    
    body{
        background-image: url("img/congruent_pentagon_red.png");
    }
</style>


{% endblock %}