{# templates/index.phtml #}
<header class="noImprimir">
    <div>
        <a class="puntero" href="javascript:history.back()">
            <img id="flecha" style="width: 64px;height: 64px;"src="img/flechaIzq.png"/>
            <span class="indicacionHF">REGRESAR</span>
        </a>
        <a href="" class="puntero">
            <img id="home" src="img/home.png" />
            <span class="indicacionHF"> INICIO</span>
        </a>
        <span id="paginaActual">{% block titulo %} Menú Principal {% endblock %}</span>
    </div>
    <div>
        <span></span>
    </div>
    <div id=""></div>
</header>
<div style="margin-bottom: 70px; "    >
    {% block cuerpo %}

    {% endblock %}
</div>
<footer class="noImprimir">
    <span id="mensaje1">VERIFICADOR DE PRECIOS</span>
    <br/>
    <span id="mensaje2">PASE SU PRODUCTO</span>
</footer>

<form id="toVerifier" method="post"  action="verificador">
    <input id="barCode" type="hidden" name="code"/>
</form>
<script>
    var codigo="";
    $(window).on('keypress',function(e){
        if(e.keyCode==13){
            $('#barCode').val(codigo);
            console.log(codigo);
            $('#toVerifier').submit();
            
        }else{
             codigo += String.fromCharCode(e.keyCode);
            // beep();
        }
        console.log(e.keyCode);
    });
</script>

