{# templates/index.phtml #}
<header>
    <div>
        <a class="puntero" href="javascript:history.back()">
            <img id="flecha" style="width: 64px;height: 64px;"src="img/flechaIzq.png"/>
            <span class="indicacionHF">REGRESAR</span>
        </a>
        <a href="" class="puntero">
            <img id="home" src="img/home.png" />
            <span class="indicacionHF"> INICIO</span>
        </a>
        <span id="paginaActual"> Menú Principal</span>
    </div>
    <div>
        <span></span>
    </div>
    <div id=""></div>
</header>
<div>
    {% block cuerpo %}

    {% endblock %}
</div>
<footer>
    <span id="mensaje1">VERIFICADOR DE PRECIOS</span>
    <br/>
    <span id="mensaje2">PASE SU PRODUCTO</span>
</footer>

