{% extends "templates/index.phtml" %}
{% block cuerpo %}

<script type="text/javascript" src="js/jssor.js"></script>
<script type="text/javascript" src="js/jssor.slider.min.js"></script>
<script type="text/javascript" src="js/InitGallery.js"></script>

<div id="slider1_container" style="position: relative; margin: 0 auto;
    top: 0px; left: 0px; width: 1300px; height: 400px; overflow: hidden;">
    <!-- Loading Screen -->
    <div u="loading" style="position: absolute; top: 0px; left: 0px;">
        <div style="filter: alpha(opacity=70); opacity: 0.7; position: absolute; display: block;
            top: 0px; left: 0px; width: 100%; height: 100%;">
        </div>
        <div style="position: absolute; display: block; background: url(../img/loading.gif) no-repeat center center;
            top: 0px; left: 0px; width: 100%; height: 100%;">
        </div>
    </div>
    <!-- Slides Container -->
    <div u="slides" style="cursor: move; position: absolute; left: 0px; top: 0px; width: 1300px;
        height: 500px; overflow: hidden;">
        <div>
            <img u="image" src="img/productos/001.jpg" />
            <div class="textoAnuncio" >
                Gran descuento en <br/>Cereales y Leche!
            </div>
        </div>
         <div>
            <img u="image" src="img/productos/002.jpg" />
            <div class="textoAnuncio" >
                Detergente al <br/>15% de descuento
            </div>
        </div>
         <div>
            <img u="image" src="img/productos/003.jpg" />
            <div class="textoAnuncio" >
                Toda la botana al 3X2
            </div>
        </div>
         <div>
            <img u="image" src="img/productos/004.jpg" />
            <div class="textoAnuncio" >
                <n>¿Sabias que?</n><br/> La miel de nuestra tienda es la más saludable
            </div>
        </div>
         <div>
            <img u="image" src="img/productos/005.jpg" />
            <div class="textoAnuncio" >
                La aceite más saludable para su hogar
            </div>
        </div>
        <!--
        <div>
            <img u="image" src="img/1920/blue.jpg" />
            <div style="position: absolute; width: 480px; height: 120px; top: 30px; left: 30px; padding: 5px;
                text-align: left; line-height: 60px; text-transform: uppercase; font-size: 50px;
                    color: #FFFFFF;">Touch Swipe Slider
            </div>
            <div style="position: absolute; width: 480px; height: 120px; top: 300px; left: 30px; padding: 5px;
                text-align: left; line-height: 36px; font-size: 30px;
                    color: #FFFFFF;">
                    Build your slider with anything, includes image, content, text, html, photo, picture
            </div>
        </div>
        -->
    </div>

    <!-- bullet navigator container -->
    <div u="navigator" class="jssorb21" style="bottom: 26px; right: 6px;">
        <!-- bullet navigator item prototype -->
        <div u="prototype"></div>
    </div>
    <!--#endregion Bullet Navigator Skin End -->

    <!-- Arrow Left -->
    <span u="arrowleft" class="jssora21l" style="top: 123px; left: 8px;">
    </span>
    <!-- Arrow Right -->
    <span u="arrowright" class="jssora21r" style="top: 123px; right: 8px;">
    </span>
    <!--#endregion Arrow Navigator Skin End -->
    <a style="display: none" href="http://www.jssor.com">Image Slider</a>
</div>
<!-- Jssor Slider End -->

<nav>
    <div>
        <a href="departamentos">
            <img src="img/localizacionDepartamentos.png">
            <span>Buscar de departamentos</span>
        </a>
        <a href="datos">
            <img src="img/datosTienda.png">
            <span>Datos de la tienda </span>
        </a>
    </div>
</nav> 


{% endblock %}