{% extends "templates/index.phtml" %}
{% block cuerpo %}
<script type="text/javascript" src="js/jquery-1.11.2.min.js"></script>
<script type="text/javascript" src="js/jssor.js"></script>
<script type="text/javascript" src="js/jssor.slider.min.js"></script>
<script type="text/javascript" src="js/InitGallery.js"></script>

<div id="slider1_container" style="position: relative; margin: 0 auto;
    top: 0px; left: 0px; width: 1300px; height: 400px; overflow: hidden;">
    <!-- Loading Screen -->
    <div u="loading" style="position: absolute; top: 0px; left: 0px;">
        <div style="filter: alpha(opacity=70); opacity: 0.7; position: absolute; display: block;
            top: 0px; left: 0px; width: 100%; height: 100%;">
        </div>
        <div style="position: absolute; display: block; background: url(../img/loading.gif) no-repeat center center;
            top: 0px; left: 0px; width: 100%; height: 100%;">
        </div>
    </div>
    <!-- Slides Container -->
    <div u="slides" style="cursor: move; position: absolute; left: 0px; top: 0px; width: 1300px;
        height: 500px; overflow: hidden;">
       
        {% for ad in ads %}
        <div>
            <a href="ads/index/{{ad.id}}">
            <img u="image" src="img/ads/{{ad.id}}" />
                <h2 class="tituloAnuncio" >
                    {{ad.title|e}}
                </h2>
                <br/>
                <div class="textoAnuncio" >
                    {{ad.description}}
                </div>
            </a>
        </div>
        {% endfor  %}
        
    </div>

    <!-- bullet navigator container -->
    <div u="navigator" class="jssorb21" style="bottom: 26px; right: 6px;">
        <!-- bullet navigator item prototype -->
        <div u="prototype"></div>
    </div>
    <!--#endregion Bullet Navigator Skin End -->

    <!-- Arrow Left -->
    <span u="arrowleft" class="jssora21l" style="top: 123px; left: 8px;">
    </span>
    <!-- Arrow Right -->
    <span u="arrowright" class="jssora21r" style="top: 123px; right: 8px;">
    </span>
    <!--#endregion Arrow Navigator Skin End -->
    <a style="display: none" href="http://www.jssor.com">Image Slider</a>
</div>
<!-- Jssor Slider End -->

<nav>
    <div>
        <a href="departamentos">
            <img src="img/localizacionDepartamentos.png">
            <span>Buscar de departamentos</span>
        </a>
        <a href="datos">
            <img src="img/datosTienda.png">
            <span>Datos de la tienda </span>
        </a>
    </div>
</nav> 
<script>
    var messagesToTalk=[];
    {% for ad in ads %}
        messagesToTalk.push({{ad.title|json_encode}});
    {% endfor  %}
</script>


{% endblock %}
