<div id="slider1_container" style="position:relative;margin:0 auto;top:0px;left:0px;width:1300px;height:500px;overflow:hidden;">
<div u="loading" style="position:absolute;top:0px;left:0px;">
<div style="filter:alpha(opacity=70);opacity:0.7;position:absolute;display:block;top:0px;left:0px;width:100%;height:100%;">
</div>
<div style="position:absolute;display:block;background:url(../img/loading.gif) no-repeat center center;top:0px;left:0px;width:100%;height:100%;">
</div>
</div>
<div u="slides" style="cursor:move;position:absolute;left:0px;top:0px;width:1300px;height:500px;overflow:hidden;">
<div>
<img u="image" src="../img/1920/red.jpg">
<div u="caption" t="NO" t3="RTT|2" r3="137.5%" du3="3000" d3="500" style="position:absolute;width:445px;height:300px;top:100px;left:600px;">
<img src="../img/new-site/c-phone.png" style="position:absolute;width:445px;height:300px;top:0px;left:0px;">
<img u="caption" t="CLIP|LR" du="4000" t2="NO" src="../img/new-site/c-jssor-slider.png" style="position:absolute;width:102px;height:78px;top:70px;left:130px;">
<img u="caption" t="ZMF|10" t2="NO" src="../img/new-site/c-text.png" style="position:absolute;width:80px;height:53px;top:153px;left:163px;">
<img u="caption" t="RTT|10" t2="NO" src="../img/new-site/c-fruit.png" style="position:absolute;width:140px;height:90px;top:60px;left:220px;">
<img u="caption" t="T" du="4000" t2="NO" src="../img/new-site/c-navigator.png" style="position:absolute;width:200px;height:155px;top:57px;left:121px;">
</div>
<div u="caption" t="RTT|2" r="-75%" du="1600" d="2500" t2="NO" style="position:absolute;width:470px;height:220px;top:120px;left:650px;">
<img src="../img/new-site/c-phone-horizontal.png" style="position:absolute;width:470px;height:220px;top:0px;left:0px;">
<img u="caption" t3="MCLIP|L" du3="2000" src="../img/new-site/c-slide-1.jpg" style="position:absolute;width:379px;height:213px;top:4px;left:45px;">
<img u="caption" t="MCLIP|R" du="2000" t2="NO" src="../img/new-site/c-slide-3.jpg" style="position:absolute;width:379px;height:213px;top:4px;left:45px;">
<img u="caption" t="RTTL|BR" x="500%" y="500%" du="1000" d="-3000" r="-30%" t3="L" x3="70%" du3="1600" src="../img/new-site/c-finger-pointing.png" style="position:absolute;width:257px;height:300px;top:80px;left:200px;">
<img src="../img/new-site/c-navigator-horizontal.png" style="position:absolute;width:379px;height:213px;top:4px;left:45px;">
</div>
<div style="position:absolute;width:480px;height:120px;top:30px;left:30px;padding:5px;text-align:left;line-height:60px;text-transform:uppercase;font-size:50px;color:#FFFFFF;">Touch Swipe Slider
</div>
<div style="position:absolute;width:480px;height:120px;top:300px;left:30px;padding:5px;text-align:left;line-height:36px;font-size:30px;color:#FFFFFF;">
Build your slider with anything, includes image, content, text, html, photo, picture
</div>
</div>
<div>
<img u="image" src="../img/1920/purple.jpg">
<div style="position:absolute;width:480px;height:120px;top:30px;left:30px;padding:5px;text-align:left;line-height:60px;text-transform:uppercase;font-size:50px;color:#FFFFFF;">Touch Swipe Slider
</div>
<div style="position:absolute;width:480px;height:120px;top:300px;left:30px;padding:5px;text-align:left;line-height:36px;font-size:30px;color:#FFFFFF;">
Build your slider with anything, includes image, content, text, html, photo, picture
</div>
</div>
<div>
<img u="image" src="../img/1920/blue.jpg">
<div style="position:absolute;width:480px;height:120px;top:30px;left:30px;padding:5px;text-align:left;line-height:60px;text-transform:uppercase;font-size:50px;color:#FFFFFF;">Touch Swipe Slider
</div>
<div style="position:absolute;width:480px;height:120px;top:300px;left:30px;padding:5px;text-align:left;line-height:36px;font-size:30px;color:#FFFFFF;">
Build your slider with anything, includes image, content, text, html, photo, picture
</div>
</div>
<div u="any" style="position:absolute;display:block;top:6px;right:170px;width:280px;height:40px;">
<a class="share-icon share-facebook" target="_blank" href="http://www.facebook.com/sharer.php?u=http://jssor.com" title="Share on Facebook"></a>
<a class="share-icon share-twitter" target="_blank" href="http://twitter.com/share?url=http://jssor.com&text=jQuery%20Image%20Slider/Slideshow/Carousel/Gallery/Banner%20javascript+html%20TOUCH%20SWIPE%20Responsive" title="Share on Twitter"></a>
<a class="share-icon share-googleplus" target="_blank" href="https://plus.google.com/share?url=http://jssor.com" title="Share on Google Plus"></a>
<a class="share-icon share-linkedin" target="_blank" href="http://www.linkedin.com/shareArticle?mini=true&url=http://jssor.com" title="Share on LinkedIn"></a>
<a class="share-icon share-stumbleupon" target="_blank" href="http://www.stumbleupon.com/submit?url=http://jssor.com&title=jQuery%20Image%20Slider/Slideshow/Carousel/Gallery/Banner%20javascript+html%20TOUCH%20SWIPE%20Responsive" title="Share on StumbleUpon"></a>
<a class="share-icon share-pinterest" target="_blank" href="http://pinterest.com/pin/create/button/?url=http://jssor.com&media=http://jssor.com/img/site/jssor.slider.jpg&description=jQuery%20Image%20Slider/Slideshow/Carousel/Gallery/Banner%20javascript+html%20TOUCH%20SWIPE%20Responsive" title="Share on Pinterst"></a>
<a class="share-icon share-email" target="_blank" href="mailto:?Subject=Jssor%20Slider&Body=Highly%20recommended%20jQuery%20Image%20Slider/Slideshow/Carousel/Gallery/Banner%20javascript+html%20TOUCH%20SWIPE%20Responsive%20http://jssor.com" title="Share by Email"></a>
</div>
</div>
<div u="navigator" class="jssorb21" style="bottom:26px;right:6px;">
<div u="prototype"></div>
</div>
<span u="arrowleft" class="jssora21l" style="top:123px;left:8px;">
</span>
<span u="arrowright" class="jssora21r" style="top:123px;right:8px;">
</span>
<a style="display:none" href="http://www.jssor.com">jQuery Slider</a>
</div>
<script>
jssor_slider1_starter('slider1_container');
</script>
<div style="height:1px;"></div>
<div class="ad_title">
<div class="ad_title_banner">
<ins id="ad_banner_728_second" class="adsbygoogle" style="display:inline-block;width:728px;height:90px" data-ad-client="ca-pub-5323311666976160" data-ad-slot="9380985535"></ins>
<ins id="ad_banner_320_second" class="adsbygoogle" style="display:inline-block;width:320px;height:50px" data-ad-client="ca-pub-5323311666976160" data-ad-slot="4773938338"></ins>
<script>
new function () {
                    var availableWidth = document.body.clientWidth || 728;
                    window.screen && window.screen.availWidth && (availableWidth = Math.max(availableWidth, window.screen.availWidth));

                    var adElementToRemove = document.getElementById(availableWidth < 728 ? "ad_banner_728_second" : "ad_banner_320_second");
                    adElementToRemove.parentNode.removeChild(adElementToRemove);

                    (adsbygoogle = window.adsbygoogle || []).push({});
                };
</script>
</div>
<div class="ad_title_caption" style="position:absolute;top:0px;left:0px;margin-left:30px;line-height:90px;font-size:26px;color:#ff8400;">
<span>Demo - Sliders</span>
</div>
</div>


<div id="slider1_container" style="position: relative; top: 0px; left: 0px; width: 200%; ">
    <!-- Slides Container -->
    <div u="slides" style="cursor: move; position: absolute; overflow: hidden; left: 0px; top: 0px; width: 100%; height: 300px;">
        <div><img src="img/promocion/001.jpg"></div>
        <div><img src="img/promocion/002.jpg"></div>
        <div><img src="img/promocion/003.jpg"></div>
    </div>
</div>


<style>
    /* http://meyerweb.com/eric/tools/css/reset/ 
   v2.0 | 20110126
   License: none (public domain)
*/

html, body, div, span, applet, object, iframe,
h1, h2, h3, h4, h5, h6, p, blockquote, pre,
a, abbr, acronym, address, big, cite, code,
del, dfn, em, img, ins, kbd, q, s, samp,
small, strike, strong, sub, sup, tt, var,
b, u, i, center,
dl, dt, dd, ol, ul, li,
fieldset, form, label, legend,
table, caption, tbody, tfoot, thead, tr, th, td,
article, aside, canvas, details, embed, 
figure, figcaption, footer, header, hgroup, 
menu, nav, output, ruby, section, summary,
time, mark, audio, video {
	margin: 0;
	padding: 0;
	border: 0;
	font-size: 100%;
	font: inherit;
	vertical-align: baseline;
}
/* HTML5 display-role reset for older browsers */
article, aside, details, figcaption, figure, 
footer, header, hgroup, menu, nav, section {
	display: block;
}
body {
	line-height: 1;
}
ol, ul {
	list-style: none;
}
blockquote, q {
	quotes: none;
}
blockquote:before, blockquote:after,
q:before, q:after {
	content: '';
	content: none;
}
table {
	border-collapse: collapse;
	border-spacing: 0;
}




    img{
        width: 100%;
    }
    body,html{
       margin:0px;
padding:0px;
width:100%;

min-height:100%;

    }
    
</style>

<script>

var options = { $AutoPlay: true };
        var jssor_slider1 = new $JssorSlider$('slider1_container', options);
</script>