{% extends "templates/index.phtml" %}

{% block titulo %} Verificador de precios {% endblock %}

{% block cuerpo %}
<a href="verificador#paginaActual"><div class="boton1"><img src="img/arriba.svg" class="botonSubir"/></div></a>
<div style="text-align: center;margin-bottom: 70px; ">

    
    <div style="
         display: inline-block;  overflow: hidden; 
         width: 700px;
         margin-top: 20px;
         border-radius: 30px;
         background-color: rgba(0,50,0,.2);
         padding: 10px;">
        <div style="" class="inlineBlock">
            <img src="img/laptop.png" style="width:300px;height:300px;float: right;">
        </div>
        <script >
        var producto={{producto|json_encode}};
                
            
        </script>
        <div style=" 
             font-family: fantasy;
             padding: 40px;
             vertical-align: top;" class="inlineBlock">
            <ul style="list-style: none; width: 300px;">
                <li><span id="codigo">{{producto.bar_code}}</span></li>
                <li><span id="nombreP" style="font-size: 30px;">{{producto.name}}</span></li>
                <br/>
                <li><a href="verificador#descripcionMostrar"id="descripcionV" 
                       style="">
                        Ver Descripcion
                    </a></li>
                
                <li style="
                    padding: 10px;
                    margin-top: 20px;
                    width: 100%;
                    vertical-align: middle;
                    background-color: rgba(57, 100, 60,.5);
                    border-radius: 30px">
                    <span style="font-size: 20px;">Precio:</span>
                    <br/>
                    <span id="precioP" style="
                          font-size: 60px;color:greenyellow;
                          text-shadow: 2px 2px 5px black;
                          
                          " >   
                        {{producto.price}}
                    </span></li>
            </ul>
        </div>

    </div>




    <div id="descripcionMostrar" style="margin-left:60px;
         color:white;
         font-size: 20px;
         margin-right:60px; 
         text-align : justify; 
         margin-bottom: 150px; 
         background-color: rgba(57, 100, 60,.5);
         border-radius: 10px;
         padding: 15px;
         " class="">
        <p>{{producto.description}}</p>
    </div><div id="promocioneslol">
        <span>Productos Similares:</span>
        <div><img src="img/laptop.png"></div>
        <div><img src="img/laptop.png"></div>
        <div><img src="img/laptop.png"></div>
        <div><img src="img/laptop.png"></div>
        <div><img src="img/laptop.png"></div>
        <div><img src="img/laptop.png"></div>
    </div>


    <script>
        var verficador = new Verficador();
    </script>



</div>
{% endblock %}
