<!DOCTYPE html>
<html>
	<head>  
            <base href="/svp/"/>
            <title>Phalcon PHP Framework</title>
            {{stylesheet_link('css/plantilla.css')}}
            {{stylesheet_link('css/jssor.css')}}
            {{ javascript_include('js/verificadorJS.js') }}
            <script type="text/javascript" src="js/jquery-1.11.2.min.js"></script>
            <a href="index.phtml"></a>
	</head>
	<body>
		{{ content() }}
	</body>
</html>