<!DOCTYPE html>
<html>
    <head>  
        <meta http-equiv="cache-control" content="max-age=0" />
        <meta http-equiv="cache-control" content="no-cache" />
        <meta http-equiv="expires" content="0" />
        <meta http-equiv="expires" content="Tue, 01 Jan 1980 1:00:00 GMT" />
        <meta http-equiv="pragma" content="no-cache" />
        <base href="/svp/"/>
        <title>Phalcon PHP Framework</title>
        {{stylesheet_link('css/plantilla.css')}}
        {{stylesheet_link('css/jssor.css')}}
        {{ javascript_include('js/verificadorJS.js') }}
        {{ javascript_include('js/jquery-1.11.2.min.js') }}
    <a href="index.phtml"></a>
</head>
<body>
    {{ content() }}
</body>
</html>
